### ISSUE TITLE
Failed to return the radical smiles at alpha-C 

### ISSUE THREAD

**Issue by lqcata** [jensengroup/xyz2mol#11] opened 2019-09-19 16:14 UTC
20
test
C       1.946483        1.206551        0.000157
C       0.557868        1.211882        0.000209
C       -0.183791       -0.000006       0.000084
C       0.557871        -1.211887       -0.000106
C       1.946488        -1.206548       -0.000175
C       2.653807        0.000002        -0.000057
H       2.485035        2.147902        0.000311
H       0.032031        2.159512        0.000486
H       0.032040        -2.159521       -0.000265
H       2.485039        -2.147900       -0.000328
H       3.737395        0.000005        -0.000165
C       -1.617056       -0.000003       -0.000038
C       -2.374708       -1.296605       0.000275
H       -3.452167       -1.122153       0.000408
H       -2.135352       -1.908833       -0.880101
H       -2.135065       -1.908601       0.880692
C       -2.374698       1.296610        -0.000331
H       -2.134393       1.908972        -0.880312
H       -3.452159       1.122170        -0.001312
H       -2.135994       1.908472        0.880480

The SMILES for above structure is: C\[C-\](C)c1ccccc1 or C\[C-\](c1ccccc1)C
But the output from xyz2mol.py is: CC(C)=C1C=CC=C[CH-]1

**Comment by jhjensen2** [comment] 2019-09-20 08:44
That's a tricky one. I'll have to think about how to fix that. Could take a while

**Comment by lqcata** [comment] 2019-09-20 11:47
Is it possible that we treat the C[C-](c1ccccc1)C as C[C-](**R**)C? Perhaps the following indirect method will work.
1) analyze the Ar group firstly; 
2) then replace it as R;
3) analyze the whole radical to get C[C-](**R**)C;
4) and replace the R back to Ar SMILES.

When Ar is replaced by the CH3 in the tricky one, the xyz2mol.py can get the right SMILES for *C(CH3)3 as C[C-](C)C. 
===============
13
test
 C                 -1.61705600   -0.00000300   -0.00003800
 C                 -2.37470800   -1.29660500    0.00027500
 H                 -3.45216700   -1.12215300    0.00040800
 H                 -2.13535200   -1.90883300   -0.88010100
 H                 -2.13506500   -1.90860100    0.88069200
 C                 -2.37469800    1.29661000   -0.00033100
 H                 -2.13439300    1.90897200   -0.88031200
 H                 -3.45215900    1.12217000   -0.00131200
 H                 -2.13599400    1.90847200    0.88048000
 C                 -0.07705600   -0.00001028   -0.00005833
 H                  0.27960104    0.49171364   -0.88091209
 H                  0.27962422    0.51696267    0.86620848
 H                  0.27960628   -1.00871224    0.01451450

**Comment by jhjensen2** [comment] 2019-09-21 11:42
But how are you going to find Ar groups if the bond orders haven't been assigned?

The problem is that there are several chains of alternating double bonds with equal length and "UA_pairs = [list(nx.max_weight_matching(G))]" returns just one arbitrary choice (that depends on atom ordering)

Right now I don't see how to implement a general fix, so I resurrected clean_charges as a hack, so your molecule works now.

I'm closing the issue, but if you find a more general fix by all means submit a pull request or open another issue

**Closed by jhjensen2** 2019-09-21 11:42 UTC
